# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataForMaster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataForMaster.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x44\x61taForMaster.proto2\x05\n\x03\x44\x46Mb\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DFM = _descriptor.ServiceDescriptor(
  name='DFM',
  full_name='DFM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=23,
  serialized_end=28,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_DFM)

DESCRIPTOR.services_by_name['DFM'] = _DFM

# @@protoc_insertion_point(module_scope)
