# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataForClient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataForClient.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x44\x61taForClient.proto\"_\n\x08MetaData\x12\x11\n\tChunkSize\x18\x01 \x01(\x05\x12\x0f\n\x07\x43hunkId\x18\x02 \x01(\x05\x12\r\n\x05inFID\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x05\x12\x10\n\x08StoreDID\x18\x05 \x01(\x05\"@\n\x12uploadChunkRequest\x12\x1b\n\x08metadata\x18\x01 \x01(\x0b\x32\t.MetaData\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\"\"\n\x13uploadChunkResponse\x12\x0b\n\x03Msg\x18\x01 \x01(\t2A\n\x03\x44\x46\x43\x12:\n\x0buploadChunk\x12\x13.uploadChunkRequest\x1a\x14.uploadChunkResponse\"\x00\x62\x06proto3')
)




_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChunkSize', full_name='MetaData.ChunkSize', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ChunkId', full_name='MetaData.ChunkId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inFID', full_name='MetaData.inFID', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='MetaData.offset', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StoreDID', full_name='MetaData.StoreDID', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=118,
)


_UPLOADCHUNKREQUEST = _descriptor.Descriptor(
  name='uploadChunkRequest',
  full_name='uploadChunkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='uploadChunkRequest.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='uploadChunkRequest.chunk', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=184,
)


_UPLOADCHUNKRESPONSE = _descriptor.Descriptor(
  name='uploadChunkResponse',
  full_name='uploadChunkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Msg', full_name='uploadChunkResponse.Msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=220,
)

_UPLOADCHUNKREQUEST.fields_by_name['metadata'].message_type = _METADATA
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.message_types_by_name['uploadChunkRequest'] = _UPLOADCHUNKREQUEST
DESCRIPTOR.message_types_by_name['uploadChunkResponse'] = _UPLOADCHUNKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'DataForClient_pb2'
  # @@protoc_insertion_point(class_scope:MetaData)
  })
_sym_db.RegisterMessage(MetaData)

uploadChunkRequest = _reflection.GeneratedProtocolMessageType('uploadChunkRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADCHUNKREQUEST,
  '__module__' : 'DataForClient_pb2'
  # @@protoc_insertion_point(class_scope:uploadChunkRequest)
  })
_sym_db.RegisterMessage(uploadChunkRequest)

uploadChunkResponse = _reflection.GeneratedProtocolMessageType('uploadChunkResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADCHUNKRESPONSE,
  '__module__' : 'DataForClient_pb2'
  # @@protoc_insertion_point(class_scope:uploadChunkResponse)
  })
_sym_db.RegisterMessage(uploadChunkResponse)



_DFC = _descriptor.ServiceDescriptor(
  name='DFC',
  full_name='DFC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=222,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='uploadChunk',
    full_name='DFC.uploadChunk',
    index=0,
    containing_service=None,
    input_type=_UPLOADCHUNKREQUEST,
    output_type=_UPLOADCHUNKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DFC)

DESCRIPTOR.services_by_name['DFC'] = _DFC

# @@protoc_insertion_point(module_scope)
