# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MasterForClient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MasterForClient.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15MasterForClient.proto\"\n\n\x08\x45mptyArg\"\x13\n\x03Str\x12\x0c\n\x04name\x18\x01 \x01(\t2)\n\x03MFC\x12\"\n\x0bgetFiletree\x12\t.EmptyArg\x1a\x04.Str\"\x00\x30\x01\x62\x06proto3')
)




_EMPTYARG = _descriptor.Descriptor(
  name='EmptyArg',
  full_name='EmptyArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=35,
)


_STR = _descriptor.Descriptor(
  name='Str',
  full_name='Str',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Str.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['EmptyArg'] = _EMPTYARG
DESCRIPTOR.message_types_by_name['Str'] = _STR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyArg = _reflection.GeneratedProtocolMessageType('EmptyArg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYARG,
  '__module__' : 'MasterForClient_pb2'
  # @@protoc_insertion_point(class_scope:EmptyArg)
  })
_sym_db.RegisterMessage(EmptyArg)

Str = _reflection.GeneratedProtocolMessageType('Str', (_message.Message,), {
  'DESCRIPTOR' : _STR,
  '__module__' : 'MasterForClient_pb2'
  # @@protoc_insertion_point(class_scope:Str)
  })
_sym_db.RegisterMessage(Str)



_MFC = _descriptor.ServiceDescriptor(
  name='MFC',
  full_name='MFC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=58,
  serialized_end=99,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFiletree',
    full_name='MFC.getFiletree',
    index=0,
    containing_service=None,
    input_type=_EMPTYARG,
    output_type=_STR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MFC)

DESCRIPTOR.services_by_name['MFC'] = _MFC

# @@protoc_insertion_point(module_scope)
