# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MasterForClient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MasterForClient.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15MasterForClient.proto\"\n\n\x08\x45mptyArg\"%\n\x03Str\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08isFolder\x18\x02 \x01(\x08\"V\n)getTrunkInfoAndAllocatedDataServerRequest\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0c\n\x04path\x18\x03 \x01(\t2\x85\x01\n\x03MFC\x12\"\n\x0bgetFiletree\x12\t.EmptyArg\x1a\x04.Str\"\x00\x30\x01\x12Z\n\"getTrunkInfoAndAllocatedDataServer\x12*.getTrunkInfoAndAllocatedDataServerRequest\x1a\x04.Str\"\x00\x30\x01\x62\x06proto3')
)




_EMPTYARG = _descriptor.Descriptor(
  name='EmptyArg',
  full_name='EmptyArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=35,
)


_STR = _descriptor.Descriptor(
  name='Str',
  full_name='Str',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Str.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isFolder', full_name='Str.isFolder', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=74,
)


_GETTRUNKINFOANDALLOCATEDDATASERVERREQUEST = _descriptor.Descriptor(
  name='getTrunkInfoAndAllocatedDataServerRequest',
  full_name='getTrunkInfoAndAllocatedDataServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='getTrunkInfoAndAllocatedDataServerRequest.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='getTrunkInfoAndAllocatedDataServerRequest.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='getTrunkInfoAndAllocatedDataServerRequest.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['EmptyArg'] = _EMPTYARG
DESCRIPTOR.message_types_by_name['Str'] = _STR
DESCRIPTOR.message_types_by_name['getTrunkInfoAndAllocatedDataServerRequest'] = _GETTRUNKINFOANDALLOCATEDDATASERVERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyArg = _reflection.GeneratedProtocolMessageType('EmptyArg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYARG,
  '__module__' : 'MasterForClient_pb2'
  # @@protoc_insertion_point(class_scope:EmptyArg)
  })
_sym_db.RegisterMessage(EmptyArg)

Str = _reflection.GeneratedProtocolMessageType('Str', (_message.Message,), {
  'DESCRIPTOR' : _STR,
  '__module__' : 'MasterForClient_pb2'
  # @@protoc_insertion_point(class_scope:Str)
  })
_sym_db.RegisterMessage(Str)

getTrunkInfoAndAllocatedDataServerRequest = _reflection.GeneratedProtocolMessageType('getTrunkInfoAndAllocatedDataServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTRUNKINFOANDALLOCATEDDATASERVERREQUEST,
  '__module__' : 'MasterForClient_pb2'
  # @@protoc_insertion_point(class_scope:getTrunkInfoAndAllocatedDataServerRequest)
  })
_sym_db.RegisterMessage(getTrunkInfoAndAllocatedDataServerRequest)



_MFC = _descriptor.ServiceDescriptor(
  name='MFC',
  full_name='MFC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=165,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFiletree',
    full_name='MFC.getFiletree',
    index=0,
    containing_service=None,
    input_type=_EMPTYARG,
    output_type=_STR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getTrunkInfoAndAllocatedDataServer',
    full_name='MFC.getTrunkInfoAndAllocatedDataServer',
    index=1,
    containing_service=None,
    input_type=_GETTRUNKINFOANDALLOCATEDDATASERVERREQUEST,
    output_type=_STR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MFC)

DESCRIPTOR.services_by_name['MFC'] = _MFC

# @@protoc_insertion_point(module_scope)
