# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\"\x19\n\x04Tree\x12\x11\n\tnode_name\x18\x01 \x01(\t\"\x11\n\x0fTreeNameRequest25\n\x07testrpc\x12*\n\x0bgetFiletree\x12\x10.TreeNameRequest\x1a\x05.Tree\"\x00\x30\x01\x62\x06proto3')
)




_TREE = _descriptor.Descriptor(
  name='Tree',
  full_name='Tree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_name', full_name='Tree.node_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=39,
)


_TREENAMEREQUEST = _descriptor.Descriptor(
  name='TreeNameRequest',
  full_name='TreeNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['Tree'] = _TREE
DESCRIPTOR.message_types_by_name['TreeNameRequest'] = _TREENAMEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tree = _reflection.GeneratedProtocolMessageType('Tree', (_message.Message,), {
  'DESCRIPTOR' : _TREE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Tree)
  })
_sym_db.RegisterMessage(Tree)

TreeNameRequest = _reflection.GeneratedProtocolMessageType('TreeNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _TREENAMEREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:TreeNameRequest)
  })
_sym_db.RegisterMessage(TreeNameRequest)



_TESTRPC = _descriptor.ServiceDescriptor(
  name='testrpc',
  full_name='testrpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=60,
  serialized_end=113,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFiletree',
    full_name='testrpc.getFiletree',
    index=0,
    containing_service=None,
    input_type=_TREENAMEREQUEST,
    output_type=_TREE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTRPC)

DESCRIPTOR.services_by_name['testrpc'] = _TESTRPC

# @@protoc_insertion_point(module_scope)
