# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protocol import test_pb2 as test__pb2


class testrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getFiletree = channel.unary_stream(
        '/testrpc/getFiletree',
        request_serializer=test__pb2.TreeNameRequest.SerializeToString,
        response_deserializer=test__pb2.Tree.FromString,
        )


class testrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getFiletree(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_testrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getFiletree': grpc.unary_stream_rpc_method_handler(
          servicer.getFiletree,
          request_deserializer=test__pb2.TreeNameRequest.FromString,
          response_serializer=test__pb2.Tree.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'testrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
